//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3H8Z-6jzpiDHQGn-SJxG0-2CZYUPnoVQ',
    appId: '1:1086021456294:web:13510b4f1fc1baf1fb3f67',
    messagingSenderId: '1086021456294',
    projectId: 'feed-forward-4aaf4',
    authDomain: 'feed-forward-4aaf4.firebaseapp.com',
    storageBucket: 'feed-forward-4aaf4.firebasestorage.app',
    measurementId: 'G-Q3QKYKX9P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXop-1m9hVDjQJ0nlZ1eFddB2fx3iMu8',
    appId: '1:1086021456294:android:95e0488e1849b231fb3f67',
    messagingSenderId: '1086021456294',
    projectId: 'feed-forward-4aaf4',
    storageBucket: 'feed-forward-4aaf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2u7LP3xwgCO5tGc6E4F4xEJruu21lX4',
    appId: '1:1086021456294:ios:d1193a184884408cfb3f67',
    messagingSenderId: '1086021456294',
    projectId: 'feed-forward-4aaf4',
    storageBucket: 'feed-forward-4aaf4.firebasestorage.app',
    iosBundleId: 'com.example.feedforward',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK2u7LP3xwgCO5tGc6E4F4xEJruu21lX4',
    appId: '1:1086021456294:ios:d1193a184884408cfb3f67',
    messagingSenderId: '1086021456294',
    projectId: 'feed-forward-4aaf4',
    storageBucket: 'feed-forward-4aaf4.firebasestorage.app',
    iosBundleId: 'com.example.feedforward',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3H8Z-6jzpiDHQGn-SJxG0-2CZYUPnoVQ',
    appId: '1:1086021456294:web:038014ab01a9c696fb3f67',
    messagingSenderId: '1086021456294',
    projectId: 'feed-forward-4aaf4',
    authDomain: 'feed-forward-4aaf4.firebaseapp.com',
    storageBucket: 'feed-forward-4aaf4.firebasestorage.app',
    measurementId: 'G-VL4Z47P3C4',
  );
}
